### ISSUE TITLE
Error updating to 3.0.7

### ISSUE THREAD

**Issue by Mika571** [Kinvey/dotnet-sdk#118]
### Description
Unable to update Xamarin Forms project from 3.0.5 to 3.0.7, it results in the following error:
`Could not install package 'PubnubPCL 3.8.5'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile259', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.`

### Tool Versions (Visual Studio / Device / OS)
Windows 10, Visual Studio 2017

**Comment by vinaygahlawat** [comment]
Hi @Mika571, sorry for the delayed update to your issue.  This is a known issue, and there is a PR currently open to address this.  I will update this issue when this fix is deployed, and thanks again for letting us know!

**Comment by vinaygahlawat** [comment]
Issue resolved with #122 and available in the `3.0.9` release. A greater range of PCL profiles are now supported, including `Profile259`.
